#! /bin/sh
set -e

PROXY_URL=""
#PROXY_URL="proxy.cantv.com.ve:80"

TO=/mirror
TO_FUSION=/mirror/RPM-fusion/

RSYNC_HOST=fedora.mirror.iweb.ca
#RSYNC_HOST=mirrors.servercentral.net
RSYNC_HOST_RPM_FUSION=download1.rpmfusion.org

RSYNC_DIR=fedora/
RSYNC_DIR_RPMfusion=rpmfusion/

LOGDIR=/mirror/log

ARCH_EXCLUDE="powerpc ppc x86_64"

#EXCLUDE="--exclude project/ --exclude x86_64/ --exclude epel/ --exclude local/ --exclude adobe/ --exclude 1/ --exclude 2/ --exclude 3/ --exclude 4/ --exclude 5/ --exclude 6/ --exclude 7/ --exclude 8/ --exclude 9/ --exclude 10/ --exclude 11/ --exclude 12/ --exclude 13/ --exclude 14/ --exclude 15/ --exclude Fedora/ --exclude RPM-fusion/ --exclude drpms/ --exclude jigdo/ --exclude el/ --exclude development/ --exclude test/ --exclude testing/ --exclude SRPMS.newkey/ --exclude ppc64.newkey/ --exclude ppc.newkey/ --exclude source.newkey/ --exclude x86_64.newkey/ --exclude Live/ --exclude ppc64/ --exclude extras/ --exclude core/ --exclude development/ --exclude SRPMS/ --exclude src/ --exclude debug/ --exclude iso/ --exclude ppc/ --exclude source/"

EXCLUDE="--exclude project/ --exclude epel/ --exclude local/ --exclude adobe/ --exclude 1/ --exclude 2/ --exclude 3/ --exclude 4/ --exclude 5/ --exclude 6/ --exclude 7/ --exclude 8/ --exclude 9/ --exclude 10/ --exclude 11/ --exclude 12/ --exclude 13/ --exclude 14/ --exclude 15/ --exclude Fedora/ --exclude RPM-fusion/ --exclude drpms/ --exclude jigdo/ --exclude el/ --exclude development/ --exclude test/ --exclude testing/ --exclude SRPMS.newkey/ --exclude ppc64.newkey/ --exclude ppc.newkey/ --exclude source.newkey/ --exclude x86_64.newkey/ --exclude Live/ --exclude ppc64/ --exclude extras/ --exclude core/ --exclude development/ --exclude SRPMS/ --exclude src/ --exclude debug/ --exclude iso/ --exclude ppc/ --exclude source/"
MAILTO=richzendy@gmail.com

LOCK_TIMEOUT=360

if [ -z $TO ] || [ -z $RSYNC_HOST ] || [ -z $RSYNC_DIR ] || [ -z $LOGDIR ]; then
        echo "One of the following variables seems to be empty:"
        echo "TO, RSYNC_HOST, RSYNC_DIR or LOGDIR"
        exit 2
fi

if ! [ -d ${TO}/project/trace/ ]; then
        # we are running mirror script for the first time
        umask 002
        mkdir -p ${TO}/project/trace
fi

HOSTNAME=`hostname -f`

LOCK="${TO}/Archive-Update-in-Progress-${HOSTNAME}"

TMP_EXCLUDE="--exclude .~tmp~/"

# Exclude architectures defined in $ARCH_EXCLUDE
for ARCH in $ARCH_EXCLUDE; do
        EXCLUDE=$EXCLUDE"\
                --exclude binary-$ARCH/ \
                --exclude disks-$ARCH/ \
                --exclude installer-$ARCH/ \
                --exclude Contents-$ARCH.gz \
                --exclude Contents-$ARCH.diff/ \
                --exclude arch-$ARCH.files \
                --exclude arch-$ARCH.list.gz \
                --exclude *_$ARCH.rpm \
                --exclude *_$ARCH.changes \
                --exclude *_$ARCH.udeb "
        if [ "$ARCH" = "source" ]; then
                SOURCE_EXCLUDE="\
                --exclude source/ \
                --exclude *.tar.gz \
                --exclude *.diff.gz \
                --exclude *.dsc "
        fi
done

# Logfile
LOGFILE=$LOGDIR/fedora-mirror.log

# Get in the right directory and set the umask to be group writable
#
cd $HOME
umask 002

# Check to see if another sync is in progress
if [ -f "$LOCK" ]; then
# Note: this requires the findutils find; for other finds, adjust as necessary
  if [ "`find $LOCK -maxdepth 1 -amin -$LOCK_TIMEOUT`" = "" ]; then
# Note: this requires the procps ps; for other ps', adjust as necessary
    if ps ax | grep '[r]'sync | grep -q $RSYNC_HOST; then
      echo "stale lock found, but a rsync is still running, aiee!"
      exit 1
    else
      echo "stale lock found (not accessed in the last $LOCK_TIMEOUT minutes), forcing update!"
      rm -f $LOCK
    fi
  else
    echo "current lock file exists, unable to start rsync!"
    exit 1
  fi
fi

touch $LOCK
# Note: on some non-Debian systems, trap doesn't accept "exit" as signal
# specification. If that's the case on your system, try using "0".
trap "rm -f $LOCK" exit

set +e

echo "Actualizando repositorios oficiales de fedora..."

# First sync /pool
RSYNC_PROXY=$PROXY_URL rsync --recursive --links --hard-links --times --delete-after --verbose --progress -h \
     $TMP_EXCLUDE $EXCLUDE $SOURCE_EXCLUDE \
     $RSYNC_HOST::$RSYNC_DIR $TO # >> $LOGFILE 2>&1
result=$?

if [ 0 != $result ] ; then
        # Now sync the remaining stuff
        RSYNC_PROXY=$PROXY_URL rsync --recursive --progress --links --hard-links --times --verbose --delay-updates --delete-after -h \
             --exclude "Archive-Update-in-Progress-${HOSTNAME}" \
             --exclude "project/trace/${HOSTNAME}" \
             $TMP_EXCLUDE $EXCLUDE $SOURCE_EXCLUDE \
             $RSYNC_HOST::$RSYNC_DIR $TO # >> $LOGFILE 2>&1

        LANG=C date -u > "${TO}/${HOSTNAME}"
else 
#       echo "ERROR: Help, something weird happened" | tee -a $LOGFILE
        echo "Mirror succesfull, mirroring exited with exitcode" $result | tee -a $LOGFILE
        echo ""
        echo ""
fi

# rsync a rpmfusion

echo "Actualizando repositorios RPMFUSION..."
RSYNC_PROXY=$PROXY_URL rsync --recursive --links --hard-links --times --delete-after --verbose --progress -h \
     $TMP_EXCLUDE $EXCLUDE $SOURCE_EXCLUDE \
     $RSYNC_HOST_RPM_FUSION::$RSYNC_DIR_RPMfusion $TO_FUSION # >> $LOGFILE 2>&1
result=$?

if [ 0 != $result ] ; then
        # Now sync the remaining stuff
       RSYNC_PROXY=$PROXY_URL rsync --recursive --progress --links --hard-links --times --verbose --delay-updates --delete-after -h \
            --exclude "Archive-Update-in-Progress-${HOSTNAME}" \
            --exclude "project/trace/${HOSTNAME}" \
            $TMP_EXCLUDE $EXCLUDE $SOURCE_EXCLUDE \
            $RSYNC_HOST_RPM_FUSION::$RSYNC_DIR_RPMfusion $TO_FUSION # >> $LOGFILE 2>&1

        LANG=C date -u > "${TO}/${HOSTNAME}"
else
#        echo "ERROR: Help, something weird happened" | tee -a $LOGFILE
        echo "mirroring exited with exitcode" $result | tee -a $LOGFILE
fi




if ! [ -z $MAILTO ]; then
        mail -s "fedora archive synced" $MAILTO < $LOGFILE
fi

#savelog $LOGFILE >/dev/null

#rm $LOCK

